language: c
env:
  matrix:
    # Note: Can't use CC variable as TravisCI will override it
    - C_COMPILER=gcc-5
    - C_COMPILER=clang-3.8
# Hint to TravisCI that we want to use their container infrastructure
sudo: false
git:
  # a commit-rate of one commit per minute causes errors, because Travis is too slow
  depth: 3
addons:
  apt:
    sources:
      # For newer gcc
      - ubuntu-toolchain-r-test
      # For Clang
      - llvm-toolchain-precise-3.8
    packages:
      # These are needed for compiling with -m32
      # otherwise including system header files might result in
      # errors (e.g. ``fatal error: bits/predefs.h: No such file or directory``)
      - libc6-dev-i386
      - gcc-5
      - clang-3.8
script:
  - ${C_COMPILER} -v --version
  - cd c/ && make -j2 CC=${C_COMPILER}
matrix:
  include:
    env: NAME="Sanity checks"
    script:
      - c/check.py
