language: c
env:
###############################################################################
  # Note: Can't use CC variable as TravisCI will override it
  - C_COMPILER=gcc
  - C_COMPILER=clang-3.7
###############################################################################
# Use TravisCI legacy infrastructure so we can install the packages we need, the apt add-ons
# doesn't work with Ubuntu 14.04 (Trusty)
sudo: required
dist: trusty
before_install:
  - sudo sh -c 'echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" >> /etc/apt/sources.list.d/llvm.list'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-multilib gcc-multilib libc6-dev-i386 clang-3.7
script:
  - CC=${C_COMPILER} scripts/travisci-build.sh
